### ISSUE TITLE
git not working

### ISSUE THREAD

**Issue by BluGitHubXD** [Lokitot/VsDaveArchived#2]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

## What version of the game are you using? Look in the bottom left corner of the main menu.
the 3.0
## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
no
## Please describe your issue. Provide extensive detail and images if possible.
![imagen](https://github.com/user-attachments/assets/99e231fb-64ac-48bd-b191-3ee78148aba5)
ALL IS IN SPANISH!

**Comment by doggywatty** [comment]
clonalo desde la github desktop, es mas recomendable que todo eso del cmd.
![image](https://github.com/user-attachments/assets/6f7c74e9-133b-469a-9299-88579572a9b4)

**Comment by BluGitHubXD** [comment]
gracias mano
